config/routes.rb
Rails.application.routes.draw do
  get '/admin', to: 'admin#admin', as: 'admin'

  resources :comments
  resources :landing, :only => ['index']
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :profiles do
    member do
      put "like", to: "profiles#match"
    end
  end

  get 'tags/:tag', to: 'profiles#index', as: :tag
  root 'landing#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  mount_uploader :logo, LogoUploader
  mount_uploader :background_image, BackgroundImageUploader

  acts_as_votable
  acts_as_taggable

  belongs_to :user

  validates :company_name, presence: true
  validates :description, length: { maximum: 100 }

  BUSINESS_TYPES=[['technology'], ['retail'], ['services'], ['restaurant']]
  STRUCTURES=[['Public spaces'], ['Place / Venue / Spot (Retail Store)'], ['Truck or van'], ['Any Place / Car / Motorcycle / Bike / Costumer Service'], ['Digital']]

  def self.list_categories
    ActsAsTaggableOn::Tag.all
  end

  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    if params[:tag]
      @profiles = Profile.tagged_with(params[:tag].downcase)
    else
      @profiles = Profile.all #where(:is_public => true)
    end
    @tags = ActsAsTaggableOn::Tag.order("name")
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    unless current_user && current_user.id == @profile.user_id
      if @profile.is_public == false
        redirect_to root_path
      end
    end
    @comment = Comment.new
  end

  # GET /profiles/new
  def new
    if current_user
      @profile = Profile.new
    else
      redirect_to new_user_registration_path
    end
  end

  # GET /profiles/1/edit
  def edit
    unless current_user && (current_user.id == @profile.user_id || current_user.admin)
      redirect_to root_path
    end
  end

  # POST /profiles
  # POST /profiles.json
  def create

    @profile = Profile.new(profile_params)
    if current_user
      @profile.user_id = current_user.id
    end

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }

      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def match
    @profile = Profile.find(params[:id])
    @profile.liked_by current_user
    redirect_to @profile
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:company_name, :description, :user_position, :type_of_business, :category, :city, :state, :logo, :background_image, :twitter, :facebook, :instagram, :url, :long_description, :brand_idea, :slogan, :hashtag, :is_public, :tag_list)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<div class="container col-md-6 col-md-offset-3">
  <%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<form>
  <div class="form-group">
    <%= f.label :company_name, "Name of Company" %>
    <%= f.text_field :company_name, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Brand Concept: Describe your Brand concept in 100 characters" %>
    <%= f.text_area :description, class: "form-control js-hundred-countdown" %>
    <span class="no-color">100</span>
  </div>

  <div class="form-group">
    <%= f.label :background_image, "Background Image: Background images must be in PNG, GIF, or JPG format. Optimal image size is 500 x 1500 pixels." %>
    <%= f.file_field :background_image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :logo, "Logo. Optimal image size is 150 x 150 pixels." %>
    <%= f.file_field :logo, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :brand_idea, "Brain Idea: The feature, product or service that makes you unique and everyone talks about. From 2 to 4 words." %>
    <%= f.text_field :brand_idea, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :slogan, 'Brand Slogan: A short and striking phrase to sell your brand or idea.' %>
    <%= f.text_field :slogan, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :long_description, "Long Description: It's time to talk about the history of your brand. We recommend use a paragraph from 200 to 550 characters." %>
    <%= f.text_area :long_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :type_of_business, 'Structure: Select the structure that best represents your company or personality' %><br>
    <%= f.select :type_of_business, options_for_select(Profile::STRUCTURES), {}, {class: "form-control"} %><br>
  </div>

  <div class="form-group">
    <%= f.label :city, 'City' %>
    <%= f.text_field :city, placeholder: "City", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :state, 'State' %>
    <%= f.select :state, options_for_select(@profile.us_states, "FL"), {}, {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label :hashtag, 'Username: The name that your brand uses on all digital platforms.' %>
    <%= f.text_field :hashtag, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :url, 'Web Address - Example: https://spotdly.com' %>
    <%= f.text_field :url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :facebook, 'Facebook Address - Example: https://facebook.com/Spotdly' %>
    <%= f.text_field :facebook, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :twitter, 'Twitter Address - Example: https://twitter.com/Spotdly' %>
    <%= f.text_field :twitter, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :instagram, 'Instagram Address - Example: https://instagram.com/Spotdly' %>
    <%= f.text_field :instagram, class: "form-control" %>
  </div>

  <% if current_user && current_user.admin %>
    <div class="form-group">
      <%= f.label :tag_list, 'Add this brand to a category' %>
      <%= f.text_field :tag_list, placeholder: 'separate multiple tags by commas', class: "form-control" %>
    </div>
  <% else %>
    <div class="form-group">
      <%= f.label :tag_list %>
      <%= f.select :tag_list, options_for_select(Profile.list_categories),{}, {class: "form-control"} %>
    </div>
  <% end %>

  <div class="form-group">
    <!-- <span class="radio-label"> -->
      <%# label_tag :true, "Profile PUBLIC:", value: true %>
    <!-- </span> -->
    <%# f.radio_button :is_public, true, :checked => true, data: { size: 'mini' } %>
    <!-- <span class="radio-label"> -->
      <%# label_tag :false, "Profile PRIVATE:", value: false %>
    <!-- </span> -->
    <%# f.radio_button :is_public, false, data: { size: 'mini' } %>
    <%= f.label :is_public, "Profile public (anyone can view) or private (only I can view)" %>
    <%= f.select :is_public, options_for_select([["public", true], ["private", false]]), {}, {class: "form-control"} %>
  </div>

  <div class="actions submit-button">
    <%= f.submit 'Create A Brand Profile', class: 'btn btn-default' %>
  </div>


<% end %>
</form>
</div>

app/views/profiles/edit.html.erb
<div class="container">
  <h1>Edit profile</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @profile %> |
  <%= link_to 'Back', profiles_path %>
</div>

app/views/profiles/index.html.erb
<%= render 'layouts/header' %><div>
  <h1 class="text-center">Discover Brands</h1>

  <div class="text-center" >
    <% @tags.each do |tag| %>
      <span data-toggle="tooltip" title="sort by group">
        <%= link_to tag.name, tag_path(:tag => tag.name) %>
      </span>
    <% end %>
  </div>

  <div id="index-page">
   <% @profiles.each do |profile| %>
    <% if profile.is_public || current_user && !profile.is_public && profile.user_id == current_user.id %>
     <% if profile.background_image.blank? %>
      <div style =" background-image: url('/assets/background.png'); background-size: cover; background-repeat: no-repeat;" class="col-md-2 col-sm-5 col-xs-11 brand-thumbnail brand-thumbnail-dimmed">
     <% else %>
      <div style =" background-image: url( '<%= profile.background_image.url %>'); background-size: cover; background-repeat: no-repeat;" class="col-md-2 col-sm-5 col-xs-11 brand-thumbnail brand-thumbnail-dimmed">
     <% end %>
      <%= link_to profile do %>
        <p id="description-thumbnail" class="text-center"><i class="fa fa-quote-left"></i> <%= profile.description %> <i class="fa fa-quote-right"></i></p>
        <% if profile.logo.blank? %>
          <div class="logo-index"><%= image_tag 'put-your-logo.png', class: 'logo-thumbnail' %></div>
        <% else %>
          <div class="logo-index"><%= image_tag profile.logo, class: 'logo-thumbnail' %></div>
        <% end %>

        <h4 id="company-name-thumbnail" class="text-center"><%= profile.company_name %></h4>
      </div>
     <% end %>
    <% end %>
   <% end %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <h2 class="text-center">The first step to create your brand, starts here.</h2>
  <%= render 'form' %>
  <%= link_to 'Back', profiles_path %>
</div>

app/views/profiles/show.html.erb
<%= render 'layouts/header' %>

<div class="background dimmed" style="<%= show_brand_background %>">
  <h2 id="description-show" class="text-center">
    <i class="fa-big fa fa-quote-left"></i><%= @profile.description %><i class=" fa-big fa fa-quote-right"></i>
  </h2>

  <div class="text-center match-stuff">
      <p class="num-matches text-center"><%= @profile.votes_for.size %> Matches</p>
    <div class="text-center">
      <%= link_to like_profile_path(@profile), method: :put, class: 'match-button' do %>
        <i class="fa fa-exchange">Match</i>
      <% end %>
    </div>
  </div>
</div>

<% if @profile.is_public == false %>
  <div class="alert alert-info">Your page is currently private. To activate, <%= link_to "edit your profile", edit_profile_path(@profile), class: 'alert-link' %></div>
<% end %>

<div class="container">
  <div class="row profile-info">
    <div class="col-md-4">
      <h1 id="company-name"><%= @profile.company_name %></h1>
      <p>
        <h3>Type of business</h3>
         <p><%= @profile.type_of_business %></p>
      </p>
      <p>
        <h3>Location</h3>
        <p><%= @profile.city %>, <%= @profile.state %></p>
      </p>
    </div>

    <div class="col-md-4 text-center">
      <p class="text-center">
        <% if @profile.logo.blank? %>
          <%= image_tag 'put-your-logo.png', class: "logo-show" %>
        <% else %>
          <%= image_tag @profile.logo.to_s, class: "logo-show" %>
        <% end %>
      </p>
      <p>
        <h3>Brand Idea</h3>
         <p><%= @profile.brand_idea %></p>
      </p>
      <p>
        <h3>Slogan</h3>
        <p><%= @profile.slogan %></p>
      </p>
      <p>
        <h3>Description</h3>
        <p><%= @profile.long_description %></p>
      </p>

    </div>

    <div class="col-md-4">
      <h2 class="text-center" id="brand-tree">Online Brand Tree</h2>
      <ul class="list-unstyled social-media">
        <% unless @profile.hashtag.blank? %>
          <li id="hashtag"><%= @profile.hashtag %></li>
        <% end %>
        <% unless @profile.url.blank? %>
          <li><i class="fa-big fa fa-globe fa-2x"></i><a href="<%= @profile.url %>" target="_blank"><%= @profile.url %></a></li>
        <% end %>
        <% unless @profile.facebook.blank? %>
          <li><i class="fa-big fa fa-facebook fa-2x"></i><a href="<%= @profile.facebook %>" target="_blank"><%= @profile.facebook %></a></li>
        <% end %>
        <% unless @profile.twitter.blank? %>
          <li><i class="fa-big fa fa-twitter fa-2x"></i><a href="<%= @profile.twitter %>" target="_blank"><%= @profile.twitter %></a></li>
        <% end %>
        <% unless @profile.instagram.blank? %>
          <li><i class="fa-big fa fa-instagram fa-2x"></i><a href="<%= @profile.instagram %>" target="_blank"><%= @profile.instagram %></a></li>
        <% end %>
      </ul>
    </div>

    <div class="col-md-12">
    <hr>
      <p>
        Share this:<%= social_share_button_tag(@profile.company_name) %>
      </p>

      <p style="float:left;">
        Category: <span class="tag-list-map add-to-token"><%= raw @profile.tag_list.map { |t| link_to t, tag_path(t)}.join(' ') %></span>
      </p>
    </div>

    <div class="col-md-12">
    <hr>
      <% if current_user %>
        <%= render 'comments/form' %>
      <% else %>
        <%= link_to "Log in to leave a comment", new_user_session_path %>
      <% end %>

      <% @comments = Comment.where(:profile_id => @profile.id) %>
      <% @comments.each do |c| %>
        <hr>
        <h4> <%= User.find(c.user_id).name %> says...</h4>
        <p><%= c.description %></p>
        <hr>
      <% end %>
    </div>

   </div>
  </div>
</div>